default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 30
  host: 
  username: 
  password: 
  port: 5432
  database: 

development:
  <<: *default

test: 
  <<: *default

staging:
  <<: *default

production:
  <<: *default